2024-08-13 17:03:34,117 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-08-13 17:03:34,117 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Configure stats pid to 26544
2024-08-13 17:03:34,117 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Loading settings from C:\Users\harsh\.config\wandb\settings
2024-08-13 17:03:34,118 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Loading settings from e:\Artificial Intelligence\Projects\Predictive-Truck-Delay-Management-in-Logistics\wandb\settings
2024-08-13 17:03:34,118 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-08-13 17:03:34,118 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-08-13 17:03:34,119 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-08-13 17:03:34,120 INFO    MainThread:26544 [wandb_init.py:_log_setup():524] Logging user logs to e:\Artificial Intelligence\Projects\Predictive-Truck-Delay-Management-in-Logistics\wandb\run-20240813_170333-n5ul238b\logs\debug.log
2024-08-13 17:03:34,121 INFO    MainThread:26544 [wandb_init.py:_log_setup():525] Logging internal logs to e:\Artificial Intelligence\Projects\Predictive-Truck-Delay-Management-in-Logistics\wandb\run-20240813_170333-n5ul238b\logs\debug-internal.log
2024-08-13 17:03:34,122 INFO    MainThread:26544 [wandb_init.py:init():564] calling init triggers
2024-08-13 17:03:34,123 INFO    MainThread:26544 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-08-13 17:03:34,123 INFO    MainThread:26544 [wandb_init.py:init():589] re-initializing run, found existing run on stack: ctotcyf5
2024-08-13 17:03:34,131 INFO    MainThread:26544 [wandb_run.py:_finish():1962] finishing run harshmp/truck-delay-classification/ctotcyf5
2024-08-13 17:03:34,138 INFO    MainThread:26544 [jupyter.py:save_history():445] not saving jupyter history
2024-08-13 17:03:34,138 INFO    MainThread:26544 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-08-13 17:03:34,139 INFO    MainThread:26544 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2024-08-13 17:03:34,139 INFO    MainThread:26544 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-08-13 17:03:34,141 INFO    MainThread:26544 [wandb_run.py:_restore():2185] restore
2024-08-13 17:03:34,142 INFO    MainThread:26544 [wandb_run.py:_restore():2191] restore done
2024-08-13 17:03:38,469 INFO    MainThread:26544 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2024-08-13 17:03:38,470 INFO    MainThread:26544 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2024-08-13 17:03:38,503 INFO    MainThread:26544 [wandb_run.py:_footer_sync_info():3796] logging synced files
2024-08-13 17:03:39,758 INFO    MainThread:26544 [wandb_init.py:init():614] starting backend
2024-08-13 17:03:39,759 INFO    MainThread:26544 [wandb_init.py:init():618] setting up manager
2024-08-13 17:03:39,773 INFO    MainThread:26544 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-08-13 17:03:39,778 INFO    MainThread:26544 [wandb_init.py:init():624] backend started and connected
2024-08-13 17:03:40,143 INFO    MainThread:26544 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-08-13 17:03:40,143 INFO    MainThread:26544 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-08-13 17:03:40,143 INFO    MainThread:26544 [wandb_init.py:init():716] updated telemetry
2024-08-13 17:03:40,268 INFO    MainThread:26544 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-08-13 17:03:40,521 INFO    MainThread:26544 [wandb_run.py:_on_init():2254] communicating current version
2024-08-13 17:03:40,860 INFO    MainThread:26544 [wandb_run.py:_on_init():2263] got version response upgrade_message: "wandb version 0.17.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-08-13 17:03:40,861 INFO    MainThread:26544 [wandb_init.py:init():800] starting run threads in backend
2024-08-13 17:03:42,102 INFO    MainThread:26544 [wandb_run.py:_console_start():2233] atexit reg
2024-08-13 17:03:42,104 INFO    MainThread:26544 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-08-13 17:03:42,104 INFO    MainThread:26544 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-08-13 17:03:42,105 INFO    MainThread:26544 [wandb_run.py:_redirect():2178] Redirects installed.
2024-08-13 17:03:42,109 INFO    MainThread:26544 [wandb_init.py:init():841] run started, returning control to user process
2024-08-13 17:14:44,189 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-08-13 17:14:44,190 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Configure stats pid to 26544
2024-08-13 17:14:44,191 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Loading settings from C:\Users\harsh\.config\wandb\settings
2024-08-13 17:14:44,191 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Loading settings from e:\Artificial Intelligence\Projects\Predictive-Truck-Delay-Management-in-Logistics\wandb\settings
2024-08-13 17:14:44,191 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-08-13 17:14:44,191 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-08-13 17:14:44,192 INFO    MainThread:26544 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-08-13 17:14:44,192 INFO    MainThread:26544 [wandb_init.py:_log_setup():524] Logging user logs to e:\Artificial Intelligence\Projects\Predictive-Truck-Delay-Management-in-Logistics\wandb\run-20240813_171444-hpcwvdts\logs\debug.log
2024-08-13 17:14:44,193 INFO    MainThread:26544 [wandb_init.py:_log_setup():525] Logging internal logs to e:\Artificial Intelligence\Projects\Predictive-Truck-Delay-Management-in-Logistics\wandb\run-20240813_171444-hpcwvdts\logs\debug-internal.log
2024-08-13 17:14:44,194 INFO    MainThread:26544 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002ABBDCC6170>
2024-08-13 17:14:44,195 INFO    MainThread:26544 [wandb_init.py:init():564] calling init triggers
2024-08-13 17:14:44,195 INFO    MainThread:26544 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-08-13 17:14:44,196 INFO    MainThread:26544 [wandb_init.py:init():589] re-initializing run, found existing run on stack: n5ul238b
2024-08-13 17:14:44,205 INFO    MainThread:26544 [wandb_run.py:_finish():1962] finishing run harshmp/truck-delay-classification/n5ul238b
2024-08-13 17:14:44,207 INFO    MainThread:26544 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-08-13 17:14:44,209 INFO    MainThread:26544 [wandb_run.py:_restore():2185] restore
2024-08-13 17:14:44,212 INFO    MainThread:26544 [wandb_run.py:_restore():2191] restore done
2024-08-13 17:14:48,122 INFO    MainThread:26544 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2024-08-13 17:14:48,122 INFO    MainThread:26544 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2024-08-13 17:14:48,133 INFO    MainThread:26544 [wandb_run.py:_footer_sync_info():3796] logging synced files
